---
title: "My first Quarto report"
author: "Your Name"
format:
  dashboard:
    orientation: columns
server: shiny
execute:
  echo: true      # show code by default
  warning: false  # hide warnings by default
  message: false  # hide messages by default
---

# Page 1

## Key Metric 1

:::{.valuebox .bg-warning style="height:20px;"}
### Revenue
$54k
:::

## Key Metric 2
::: {.valuebox .bg-warning style="height:20px;"}
### New Users
1,200
:::

# Page 2

## Sales Over Time {width=70%}
::: {.card title="Sales Over Time" .bordered}
```{r}
#| echo: false
library(leaflet)

leaflet() |>
  addTiles() |>
  addMarkers(
    lng = -2.4233, lat = 52.7868,
    popup = "Harper Adams University"
  )
```
:::

## Side Panel {width=30%}
::: {.panel-tabset}
### Histogram
```{r}
#| echo: false
library(ggplot2)
hist(mtcars$mpg)
```

**Some notes**  
Bottom Row: Summary Stats The average unemployment rate in this dataset is `r mean(economics$unemploy)` thousands. This helps provide context to the chart above.

### Another one

```{r}
#| echo: false
library(ggplot2)
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 2, fill = "skyblue", color = "white") +
  theme_minimal()
```
:::

# Page 3

## {.sidebar}

```{r}
#| echo: false
selectInput("plot_choice", "Select Plot:",
            choices = c("Iris Petal" = "iris", 
                        "Mtcars HP vs MPG" = "mtcars"))
```

## Column

```{r}
#| echo: false
library(plotly)
library(shiny)
plotlyOutput("main_plot")
```

```{r}
#| context: server
library(plotly)
output$main_plot <- renderPlotly({
  if (input$plot_choice == "iris") {
    plot_ly(iris, x = ~Petal.Length, y = ~Petal.Width, color = ~Species,
            type = 'scatter', mode = 'markers') %>%
      layout(title = "Iris Petal Length vs Width")
  } else {
    plot_ly(mtcars, x = ~hp, y = ~mpg, color = ~factor(cyl), 
            type = 'scatter', mode = 'markers') %>%
      layout(title = "Horsepower vs MPG (Interactive)")
  }
})
```